language: rust
script:
- cargo build --verbose --all
- cargo test --verbose --all --  --nocapture
- bash cli_test.sh
- make build
deploy:
  provider: cargo
  on:
    tags: true
  token:
    secure: SepazjYm8IWOhbYuE+5bB07KQ40ts0h2Y23Hlt7nrVLjIP1UFFQ73yOtDhb/6A6SMeTcRIXNDT5JmGEaarfVlxByJw55dq+VUZxpX9Zr3SRrXwgbdsJHwMyRbhq6A7Xhygq23MMFj0enXLgDPAITMFlNbTbho3L/ThOwzrltXHY3gpw+Nhb8w2Dt2mqnBDUOQvWXMYoGwe2Hseat4SBRMW3XpN/YtaPQX9VNNVN2vg0HOLftHfL9jnbicaO3MK6OssFa7QbpNlmN6i+xFiJzvaCpBOjd83WnpQa/982qQ5uq+7eO4bzZrPW48KKFmnCK5IzOe7kotn8CO5GGl0HyejECsyfh71GH3fWFcZIiqKHYwJ2nE8B56I4PthjIhRncK0NxAJOL/QkNQqbUUdnHqviWDtG4Z9I9iPlwePChvhMzH7blbu9P1ynFXbNeDlVOplaDjO9Bcca1QONY6Aoq1sj6P3QlRI7U9phK38F24FKkRbhEKcOuQekmm5B8OXPcScLxfswP5AODopaMg7RE3uOIhWw5tamRR2o2VirN/YRZyG1pAnzR0Ki9zq+09EUNdd7IgkvYJMW3JlAIZW0MMAcnoufNNfaq5aQyI85gK9Zqkz54OTLKxy4wCwxhVWan4we5Gtgt14q9bFxE/37sNYjK7JOnB4BkAjJHFUgQ8vg=
